# Generated by Django 2.2.2 on 2019-06-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=15)),
                ('released', models.DateField(null=True)),
                ('genre', models.CharField(max_length=250)),
                ('total_comments', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['total_comments'],
            },
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies_app.Movie')),
            ],
        ),
    ]
